### ISSUE TITLE
Unknown category error

### ISSUE THREAD

**Issue by biomagic** [CloudRail/cloudrail-si-php-sdk#1]
Hello.
I have a problem. When I use category property I see this error:
`Fatal error: Uncaught CloudRail\Error\IllegalArgumentError: Illegal argument used: Unknown category. in ...\vendor\cloudrail\library-php\src\Service\GooglePlaces.php`
Without category all work fine.
My code:
```
$cr_service = load_cloudrail_service('GooglePlaces');
$retrievedPOIs = $cr_service->getNearbyPOIs(50.45594, 30.465612, 40000, '', ['restaurant']);

function load_cloudrail_service($serviceName = 'Foursquare') {
  global $options;

  Settings::$licenseKey = $options['cr_key'];

  switch ($serviceName) {
    case 'Foursquare':
    $result = new Foursquare( $options['fsquare_id'], $options['fsquare_secret'] );
    break;
    case 'Yelp':
    $result = new \CloudRail\Service\Yelp( $options['yelp_key'] );
    break;
    case 'GooglePlaces':
    $result = new GooglePlaces( $options['gplaces_key'] );
    break;
  }
  return $result;
}
```
The same error with other services. What wrong? Thank you.
Best regards,
Yura

**Comment by fel-cesar** [comment]
I dont know if you posted the whole class code, but it seems that the import is not being done properly.
To avoid the unknown category error be sure that you loaded the proper classes:

If integrated through **composer** you can load all classes using the default autoloader, and you just need to specify what categories are you using with the require (or require_once) statement:

```php
require 'vendor/autoload.php';
use CloudRail\Settings;
use CloudRail\Service\GooglePlaces;
```

**Comment by biomagic** [comment]
Thank you for update to 1.0.2 version. It helped. But when I had tried to update version I have recieved incorrect version of cloudrail. To avoid this issue just remove composer.lock or use command composer install update to update dependencies in lock file.
